<h1 
    style="font-family: 'Courier New', Courier, monospace; 
    font-size:60px;
    text-align: center;">
    QUIZ F
</h1>

<h2 style="font-family: 'Courier New', Courier, monospace; font-size:40px;">
    Exercises 01:
</h2>
<p style="font-family: 'Courier New', Courier, monospace;">
Complete the following function (containing only one instruction starting with return) so that it returns True if n is even and False otherwise.
For example:
</p>
<table style="font-family: 'Courier New', Courier, monospace;">
    <thead>
        <tr>
            <th>Test</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>print(is_even(-1))</td>
            <td>False</td>
        </tr>
        <tr>
            <td>print(is_even(0))</td>
            <td>True</td>
        </tr>
        <tr>
            <td>print(is_even(111))</td>
            <td>False</td>
        </tr>
        <tr>
            <td>print(is_even(100))</td>
            <td>True</td>
        </tr>
    </tbody>
</table>

In [1]:
def is_even(n: int):
    return n % 2 == 0

data = [-1, 0, 111, 100]

for d in data:
    print(is_even(d))

False
True
False
True

<h2 style="font-family: 'Courier New', Courier, monospace; font-size:40px;">
    Exercises 02:
</h2>
<p style="font-family: 'Courier New', Courier, monospace;">
The following table represents the tariffs to rent a car
</p>
<table style="font-family: 'Courier New', Courier, monospace;">
    <thead>
        <tr>
            <th>Time</th>
            <th>24 hours</th>
            <th>2 days</th>
            <th>3 days</th>
            <th>4 days</th>
            <th>Every extra day</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Euro</td>
            <td>39.99</td>
            <td>79.99</td>
            <td>120</td>
            <td>160</td>
            <td>40</td>
        </tr>
    </tbody>
</table>
<p style="font-family: 'Courier New', Courier, monospace;">
Write a function rent(days) that takes an integer number of days of rent and computes the total cost.
</p>
<p style="font-family: 'Courier New', Courier, monospace;">
The function always returns a float (if days &lt; 1, return 0.0).
</p>
<p style="font-family: 'Courier New', Courier, monospace;">
For example:
</p>
<table style="font-family: 'Courier New', Courier, monospace;">
    <thead>
        <tr>
            <th>Test</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>print(rent(-2))</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>print(rent(0))</td>
            <td>0.0</td>
        </tr>
        <tr>
            <td>print(rent(1))</td>
            <td>39.99</td>
        </tr>
        <tr>
            <td>print(rent(2))</td>
            <td>79.99</td>
        </tr>
        <tr>
            <td>print(rent(3))</td>
            <td>120.0</td>
        </tr>
        <tr>
            <td>print(rent(4))</td>
            <td>160.0</td>
        </tr>
        <tr>
            <td>print(rent(5))</td>
            <td>200.0</td>
        </tr>
        <tr>
            <td>print(rent(10))</td>
            <td>400.0</td>
        </tr>
    </tbody>
</table>

In [7]:
extra_day = 40
defined_days = {
    1: 39.99,
    2: 79.99,
    3: 120,
    4: 160,
}

def rent(days: int) -> float:
    if days in defined_days:
        return float(defined_days[days]) 
    else:
        return float(defined_days[3] + (days - 3) * extra_day) if days > 0 else float(0)
    
data = [-2, 0, 1, 2, 3, 4, 5, 10]

for d in data:
    print(rent(d))

0.0
0.0
39.99
79.99
120.0
160.0
200.0
400.0

<h2 style="font-family: 'Courier New', Courier, monospace; font-size:40px;">
    Exercise 03:
</h2>
<p style="font-family: 'Courier New', Courier, monospace;">
Write a function length_multiple(s,n) that takes a string and an integer and returns True if the length of the string is multiple of the integer, and False otherwise.
</p>
<p style="font-family: 'Courier New', Courier, monospace;">
For example:
</p>
<table style="font-family: 'Courier New', Courier, monospace;">
    <thead>
        <tr>
            <th>Test</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>print(length_multiple("Cremona", 5))</td>
            <td>False</td>
        </tr>
        <tr>
            <td>print(length_multiple("Cremona", 7))</td>
            <td>True</td>
        </tr>
        <tr>
            <td>print(length_multiple("Python", 3))</td>
            <td>True</td>
        </tr>
        <tr>
            <td>print(length_multiple("Cremona", 1))</td>
            <td>True</td>
        </tr>
        <tr>
            <td>print(length_multiple("Python", 0))</td>
            <td>False</td>
        </tr>
        <tr>
            <td>print(length_multiple("", 0))</td>
            <td>False</td>
        </tr>
        <tr>
            <td>print(length_multiple("", 42))</td>
            <td>True</td>
        </tr>
        <tr>
            <td>print(length_multiple("Ciao", -2))</td>
            <td>True</td>
        </tr>
    </tbody>
</table>

<h2 style="font-family: 'Courier New', Courier, monospace; font-size:40px;">
    Exercise 04:
</h2>
<p style="font-family: 'Courier New', Courier, monospace;">
Write a function solve_linear(a,b) that takes two floats a and b and solves the linear equation ax+b=0.
</p>
<p style="font-family: 'Courier New', Courier, monospace;">
If the equation is inconsistent, return the string inconsistent, while if it has infinite solutions, the string infinite
</p>
<p style="font-family: 'Courier New', Courier, monospace;">
For example:
</p>
<table style="font-family: 'Courier New', Courier, monospace;">
    <thead>
        <tr>
            <th>Test</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>print(solve_linear(5,2.5))</td>
            <td>-0.5</td>
        </tr>
        <tr>
            <td>print(solve_linear(0,0))</td>
            <td>infinite</td>
        </tr>
        <tr>
            <td>print(solve_linear(0,3.14))</td>
            <td>inconsistent</td>
        </tr>
    </tbody>
</table>

<h2 style="font-family: 'Courier New', Courier, monospace; font-size:40px;">
    Exercise 05:
</h2>
<p style="font-family: 'Courier New', Courier, monospace;">
Write a function solve_quadratic(a,b,c) that takes three floats a, b and c and solves (for real solutions only) the quadratic equation ax<sup>2</sup>+bx+c=0. The function returns a float if there is one solution, two floats for two solutions, and a string in the other cases:
</p>
<p style="font-family: 'Courier New', Courier, monospace;">
If the equation is inconsistent, return the string inconsistent, while if it has infinite solutions, the string infinite. If the discriminant b<sup>2</sup>−4ac&lt;0, returns the string complex.
</p>
<p style="font-family: 'Courier New', Courier, monospace;">
If a=0, the program should still work to solve the linear equation bx+c=0.
</p>
<p style="font-family: 'Courier New', Courier, monospace;">
For example:
</p>
<table style="font-family: 'Courier New', Courier, monospace;">
    <thead>
        <tr>
            <th>Test</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>print(solve_quadratic(0,0,0))</td>
            <td>infinite</td>
        </tr>
        <tr>
            <td>print(solve_quadratic(0,0,3))</td>
            <td>inconsistent</td>
        </tr>
        <tr>
            <td>print(solve_quadratic(0,-3.5,7))</td>
            <td>2.0</td>
        </tr>
        <tr>
            <td>print(solve_quadratic(1,2,3))</td>
            <td>complex</td>
        </tr>
        <tr>
            <td>print(solve_quadratic(5,6,1))</td>
            <td>(-1.0, -0.2)</td>
        </tr>
    </tbody>
</table>